### ISSUE TITLE
Conditions do not update

### ISSUE THREAD

**Issue by StarHorder** [rumangerst/CSLMusicModStationCreator#2]
I cannot create or edit conditions, I have one condition, labelled Night, that ranges hour 18 to hour 6.

![image](https://user-images.githubusercontent.com/11035862/32146670-4c0efba2-bcb1-11e7-8e8e-e0410c75fa57.png)

If I set it to range from 6 to 18, save, and then open the file again, the condition will update. otherwise, it will still display 18 to 6.

**Comment by rumangerst** [comment]
Can you try the new bugfix release (1.0.2.2)?

**Comment by StarHorder** [comment]
Yeah, that's got it, thanks.
