### ISSUE TITLE
Unable to create conditions

### ISSUE THREAD

**Issue by StarHorder** [rumangerst/CSLMusicModStationCreator#3]
In relation to the previous issue, I am unable to create any conditions.

![image](https://user-images.githubusercontent.com/11035862/32146631-ade165f0-bcb0-11e7-961a-4fd05c750cda.png)

The drop down menu itself functions properly, but the buttons it contains do not function, aside from being highlighted.

**Comment by rumangerst** [comment]
Can you try the new bugfix release (1.0.2.2)?

**Comment by StarHorder** [comment]
I was using that version, sadly

**Comment by rumangerst** [comment]
No, I pushed a new version ~15min ago where I added some code that could fix it

**Comment by StarHorder** [comment]
Yeah, that's got it.
